version: '3'
volumes:
  psql-data:

services:
  web:
    image: hitalos/laravel:latest
    container_name: php-app
    ports:
        - 80:80
    volumes:
        - ./:/var/www
    env_file:
        - ./env
    depends_on:
        - postgres
    networks:
      app-env:

  #php-app:
  #  build: ./app
  #  image: myapp
  #  container_name: php-app
  #  env_file:
  #    - ./env
  #  depends_on:
  #    - postgres
  #  command: ["./wait-for-postgres.sh", "", "apache2-foreground"]
  #  ports:
  #    - 80:80
  #  networks:
  #    app-env:

  postgres:
    image: postgres:9.6
    container_name: postgres
    env_file:
      - ./env
    volumes:
      - ./postgres/script/:/docker-entrypoint-initdb.d
      - psql-data:/var/lib/posgresql/data
    networks:
      app-env:
      interface:

  pgadmin:
    image: fenglc/pgadmin4
    container_name: pgadmin
    env_file:
      - ./env
    depends_on:
      - postgres
    ports:
      - 5050:5050
    environment:
      - DEFAULT_USER=pgadmin@mail.com
      - DEFAULT_PASSWORD=mypassword
    networks:
      interface:

networks:
  app-env:
  interface:
